hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar & swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("[workspace 2 silent] zen-browser")
    hl.exec_cmd("[workspace 10 silent] Telegram")
    hl.exec_cmd("[workspace 10 silent] discord")
    hl.exec_cmd("[workspace 3 silent] ~/Throne/Throne")
end)
