hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar & swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("[workspace 2 silent] zen-browser")
    hl.exec_cmd("[workspace 7 silent] Telegram")
    hl.exec_cmd("[workspace 10 silent] discord")
    hl.exec_cmd("[workspace 3 silent] ~/Throne/Throne")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
