general {
    hide_cursor = true
    ignore_empty_input = true
    no_fade_in = true
    no_fade_out = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 8
    contrast = 1.0
    brightness = 0.85
    vibrancy = 0.15
    color = rgba(0f0f10cc)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 64
    font_family = JetBrains Mono Bold
    color = rgba(f5f5f5ff)
    position = 0, 125
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    font_size = 14
    font_family = JetBrains Mono Bold
    color = rgba(c7c7c7dd)
    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 44
    outline_thickness = 1
    fade_on_empty = true
    fade_timeout = 2500
    font_family = JetBrains Mono Bold
    dots_center = true
    dots_rounding = -1
    dots_spacing = 0.2
    outer_color = rgba(ffffff18)
    inner_color = rgba(141414cc)
    font_color = rgba(fafafaee)
    check_color = rgba(ffffff26)
    fail_color = rgba(ff0000dd)
    placeholder_text = Password
    hide_input = false
    rounding = 10
    position = 0, -90
    halign = center
    valign = center
}
