windowrule = match:class discord, workspace 8
windowrule = match:class org.telegram.desktop, workspace 5
windowrule = match:class zen, workspace 2
windowrule {
  name = windowrule-2
  float = on
  pin = on
  match:title = ^(Picture(-|\s)in(-|\s)(p|P)icture)$
}
windowrule {
  name = windowrule-8
  float = on
  match:title = Bitwarden
}
windowrule {
	name = windowrule-9
	float = on
	match:class=^steam$
}
windowrule {
	name = windowrule-9
	float = on
	match:class=jetbrains-toolbox
}
